### PR TITLE
Add autoupdater and use README generator

### PR DESCRIPTION
**Pull request by tituspijean**
🪄 

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Gredin67** [comment]
@tituspijean is this able to upgrade the config file if some parameter is removed/added?

**Comment by Gredin67** [comment]
@tituspijean see https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/pull/51/files#diff-cc6ff10f70311db9bd57e102b0f7a2258df3266a18837e4489daa366210cb31b

**Comment by tituspijean** [comment]
I guess anything is possible, but it will require a bit of bash/git black magic. 😇

**Comment by Gredin67** [comment]
!testme

**Comment by Gredin67** [comment]
@tituspijean how to auto-update the README since testing was upgraded?

**Comment by tituspijean** [comment]
I've force-pushed my commits so that the bot is triggered again and updates the READMEs. 😉

**Pull request merged**
