### PR TITLE
Testing

### LINKED ISSUE #34: Unknown error while logging in: error decoding login resp ["Cmd",{"type":"update"}]
Hello, the bot suddenly stopped working and gave the following error message:

Unknown error while logging in: error decoding login resp ["Cmd",{"type":"update"}]: json: cannot unmarshal array into Go value of type map[string]interface {}
Your WhatsApp connection was closed with websocket status code 1000. Use the reconnect command to reconnect.

The raw data is:
<pre>{
  "type": "m.room.message",
  "room_id": "!abcdefg1234567:foo.com",
  "sender": "@whatsappbot:foo.com",
  "content": {
    "msgtype": "m.text",
    "body": "Your WhatsApp connection was closed with websocket status code 1000. Use the `reconnect` command to reconnect.",
    "format": "org.matrix.custom.html",
    "formatted_body": "Your WhatsApp connection was closed with websocket status code 1000. Use the <code>reconnect</code> command to reconnect."
  },
  "origin_server_ts": 123456789,
  "unsigned": {
    "age": 182
  },
  "event_id": "$abc-a0_AbCK-abc123",
  "user_id": "@whatsappbot:foo.com",
  "age": 182
}</pre>

Have you any Idea, what could cause the problem?

### PR DESCRIPTION
**Pull request by Gredin67**
## Problem
- #34 

## Solution
- upgrade to 0.1.10

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/mautrix_whatsapp_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by Gredin67** [comment]
!testme

**Comment by centralscrutinizer21** [comment]
working fine for me
upgraded with
``sudo yunohost app upgrade mautrix_whatsapp -u https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/tree/testing --debug``
this command should also be corrected in the README.md  Developer info section

**Comment by axac** [comment]
it's work fine, thank you fit your quickly fix

**Comment by Gredin67** [comment]
Thanks for testing and feedback

**Comment by svenbrier** [comment]
I installed the update in YUNOHOST today. Thank you very much @Gredin67 for fixing this bug!

**Pull request merged**
