### PR TITLE
Upgrade to 0.8.6

### PR DESCRIPTION
**Pull request by Gredin67**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Gredin67** [comment]
!testme

**Comment by Gredin67** [comment]
@thardev you forgot to manage migration of `print_level` to `print_min `at upgrade. And/or to change the parameter name in the config
```

An error prevents the configuration panel from being displayed:

Config panel question 'print_level' should be initialized with a value during install or upgrade.

Please report this error to the YunoHost team to get it fixed!
```

**Comment by Gredin67** [comment]
my bad, it is solved in testing already

**Comment by Gredin67** [comment]
lgtm

**Comment by thardev** [comment]
Hi @Gredin67

Yes, I solved it already but I forgot to create the MR from testing to master. I'll merge this now 🙂

**Review by thardev — APPROVED** [review]

**Pull request merged**
