### PR TITLE
Upgrade to version 0.4.0 (#54)

### PR DESCRIPTION
**Pull request by Gredin67**
* Upgrade to v0.4.0

* Auto-update README

* change maintainer to thardev

* check upgrade from 0.2.4 and 0.3.0

* update config to 0.4.0

Co-authored-by: yunohost-bot <yunohost-bot@users.noreply.github.com>
Co-authored-by: yunohost-bot <yunohost@yunohost.org>
Co-authored-by: Gredin67 <gredin67@sans-nuage.fr>

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Gredin67** [comment]
!testme !bullseyetestme

**Comment by Gredin67** [comment]
fresh install OK on Raspberry pi 3b+ Yunohost 4.3

**Comment by Gredin67** [comment]
upgrade OK from 0.3.0 to 0.4.0 on x64 Yunohost 11

**Comment by thardev** [comment]
Hey @Gredin67 thanks a lot for your help! :) 
Should I merge it? I checked the code and it looks good to me

**Comment by Gredin67** [comment]
> Hey @Gredin67 thanks a lot for your help! :) Should I merge it? I checked the code and it looks good to me

yep, go for it, the robot did most of the work ;)

**Comment by thardev** [comment]
Version v0.5.0 came out, is handled on #57 :)

**Pull request closed without merging**
