### PR TITLE
Use nonappend instead of non-append

### PR DESCRIPTION
**Pull request by thardev**
## Problem

- See #59 

## Solution

- Add missing --nonappend param to ynh_use_logrotate in upgrade script

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by thardev** [comment]
Hi @Salamandar I'll appreciate a lot if you could have a look here before I merge it :)
I checked on my test box (Debian Buster with YunoHost 4.3.6.3 (stable)) and with the `--nonappend` option doesn't seem to work... only using `--non-append` it works. I guess that version is not supported anymore right?

**Comment by Salamandar** [comment]
That's weird because --nonappend is supposed to be the "newly" supported argument. I'll ask around.

**Review by Salamandar — APPROVED** [review]

**Comment by MayeulC** [comment]
> That's weird because --nonappend is supposed to be the "newly" supported argument. I'll ask around.

Did you ask around?

**Comment by Salamandar** [comment]
Ah, yes, forgot about it. I did, and it's supposed to work…

**Comment by thardev** [comment]
@MayeulC @Salamandar I had a discussion with @alexAubin.
He provided a fix here: https://github.com/YunoHost/yunohost/blob/e1cbe21cd1553b6a788d18a95e2bdb67876b05d5/helpers/logrotate#L20
and it should be there since 11.0.9.6:
https://github.com/YunoHost/yunohost/blob/e1cbe21cd1553b6a788d18a95e2bdb67876b05d5/debian/changelog#L37

So hopefully that should fix this issue :)

**Comment by MayeulC** [comment]
Thanks for the answers!
Okay, well, I changed my mautrix_signal_ynh patch to use `--nonappend` on buster as I saw that code too :)

I also made a patch for ynh4, but I don't think many people will use it.

**Pull request merged**
