### PR TITLE
Testing Upgrade 0.1.7

### PR DESCRIPTION
**Pull request by oufmilo**
Upgrade 0.1.7

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/APP_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by oufmilo** [comment]
!testme

**Comment by Gredin67** [comment]
!testme

**Comment by oufmilo** [comment]
!testme

**Comment by oufmilo** [comment]
!testme

**Comment by Gredin67** [comment]
I'm wondering if the CI is running a test on the testing branch of your repo or the Yunohost-Apps repo... @alexAubin ?

**Comment by Gredin67** [comment]
!testme

**Comment by Gredin67** [comment]
Testing synapse bridges with the CI is not great because of the dependency to synapse. I tried an upgrade on a test server.
https://paste.yunohost.org/raw/uzisolobun
```
2021-06-18 19:38:41,857: WARNING - go: downloading golang.org/x/sys v0.0.0-20210603081109-ebe580a85c40
2021-06-18 19:41:33,810: WARNING - # maunium.net/go/mautrix-whatsapp
2021-06-18 19:41:33,811: WARNING - ./asmux.go:90:29: cannot use func literal (type func()) as type func(int) in assignment
2021-06-18 19:41:33,812: WARNING - ./asmux.go:100:45: cannot use &state (type *AsmuxPong) as type *BridgeState in argument to user.prevBridgeStatus.shouldDeduplicate
2021-06-18 19:41:33,812: WARNING - ./asmux.go:109:25: cannot use &state (type *AsmuxPong) as type *BridgeState in assignment
2021-06-18 19:41:33,813: WARNING - ./asmux.go:152:24: cannot use &resp (type *AsmuxPong) as type *BridgeState in assignment
2021-06-18 19:41:33,814: WARNING - ./bridgestate.go:94:19: (*User).setupAdminTestHooks redeclared in this block
2021-06-18 19:41:33,816: WARNING - 	previous declaration at ./asmux.go:75:6
2021-06-18 19:41:33,817: WARNING - ./bridgestate.go:98:28: (*User).setupAdminTestHooks.func1 redeclared in this block
2021-06-18 19:41:33,818: WARNING - 	previous declaration at ./asmux.go:79:28
2021-06-18 19:41:33,819: WARNING - ./bridgestate.go:111:31: (*User).setupAdminTestHooks.func2 redeclared in this block
2021-06-18 19:41:33,819: WARNING - 	previous declaration at ./asmux.go:90:31
2021-06-18 19:41:33,885: DEBUG - + ynh_exit_properly
```

**Comment by Gredin67** [comment]
I updated the config file https://github.com/tulir/mautrix-whatsapp/compare/v0.1.6...v0.1.7

**Comment by Gredin67** [comment]
!testme

**Comment by Gredin67** [comment]
Here is the log of an install on my test server
https://paste.yunohost.org/raw/behulureru

**Pull request merged**
