### PR TITLE
[fix] attempt to package_check

### PR DESCRIPTION
**Pull request by tituspijean**
Attempting to fix package_check with pre-install commands

### CODE REVIEW

**Comment by Gredin67** [comment]
well my buster branch gives:
```
Package linter:                  FAIL
Installation:                    SUCCESS
Deleting:                        SUCCESS
Installation in a sub path:      Not evaluated.
Deleting from a sub path:        Not evaluated.
Installation on the root:        SUCCESS
Deleting from root:              SUCCESS
Upgrade:                         FAIL
Installation in private mode:    Not evaluated.
Installation in public mode:     SUCCESS
Multi-instance installations:    SUCCESS
Malformed path:                  Not evaluated.
Port already used:               SUCCESS
Backup:                          SUCCESS
Restore:                         FAIL
Change URL:                      Not evaluated.
Actions and config-panel:        Not evaluated.
2020-09-22 21:25:31 URL:https://raw.githubusercontent.com/YunoHost/apps/master/apps.json [97254/97254] -> "/home/gaut/package_check/list.json" [1]
grep: /home/gaut/package_check/levels.json: Aucun fichier ou dossier de ce type
Level of this application: 2 ()
	   Level 1: 1
	   Level 2: 1
	   Level 3: 0
	   Level 4: 0
	   Level 5: 0
	   Level 6: 1
	   Level 7: 0
	   Level 8: 0
	   Level 9: 0
	   Level 10: 0
You can find the complete log of these tests in /home/gaut/package_check/Complete.log
Global working time for all tests: 38 minutes, 40 seconds (21:25:31).
Disable iptables rules.
Disable the network bridge.
```

And your PR :stuck_out_tongue: : 
```
Package linter:                  FAIL
Installation:                    FAIL
Deleting:                        FAIL
Installation in a sub path:      Not evaluated.
Deleting from a sub path:        Not evaluated.
Installation on the root:        FAIL
Deleting from root:              FAIL
Upgrade:                         Not evaluated.
Installation in private mode:    Not evaluated.
Installation in public mode:     Not evaluated.
Multi-instance installations:    Not evaluated.
Malformed path:                  Not evaluated.
Port already used:               Not evaluated.
Backup:                          Not evaluated.
Restore:                         Not evaluated.
Change URL:                      Not evaluated.
Actions and config-panel:        Not evaluated.
This app doesn't respect the YEP 1.7 ! (https://yunohost.org/#/packaging_apps_guidelines_fr)
2020-09-22 21:32:08 URL:https://raw.githubusercontent.com/YunoHost/apps/master/apps.json [97254/97254] -> "/home/gaut/package_check/list.json" [1]
mautrix-whatsapp for the repository https://github.com/tituspijean/mautrix-whatsapp_ynh can't be found in the app list.
grep: /home/gaut/package_check/levels.json: Aucun fichier ou dossier de ce type
Level of this application: 0 ()
	   Level 1: 0
	   Level 2: 0
	   Level 3: 0
	   Level 4: 0
	   Level 5: 0
	   Level 6: 0
	   Level 7: 0
	   Level 8: 0
	   Level 9: 0
	   Level 10: 0
You can find the complete log of these tests in /home/gaut/package_check/Complete.log
Global working time for all tests: 3 minutes, 5 seconds (21:32:08).
Disable iptables rules.
Disable the network bridge.
```

Here is the full log: https://paste.yunohost.org/qabatuweqe.erl

**Comment by Gredin67** [comment]
Will you further check or can I first merge my buster branch? You can still merge your PR later in Master.

**Comment by Gredin67** [comment]
Last status of buster branch this morning : 
```
Package linter:                  SUCCESS
Installation:                    SUCCESS
Deleting:                        SUCCESS
Installation in a sub path:      Not evaluated.
Deleting from a sub path:        Not evaluated.
Installation on the root:        SUCCESS
Deleting from root:              SUCCESS
Upgrade:                         FAIL
Installation in private mode:    Not evaluated.
Installation in public mode:     SUCCESS
Multi-instance installations:    SUCCESS
Malformed path:                  Not evaluated.
Port already used:               SUCCESS
Backup:                          SUCCESS
Restore:                         FAIL
Change URL:                      Not evaluated.
Actions and config-panel:        Not evaluated.
2020-09-23 07:46:52 URL:https://raw.githubusercontent.com/YunoHost/apps/master/apps.json [97254/97254] -> "/home/gaut/package_check/list.json" [1]
grep: /home/gaut/package_check/levels.json: Aucun fichier ou dossier de ce type
Level of this application: 2 ()
	   Level 1: 1
	   Level 2: 1
	   Level 3: 0
	   Level 4: 0
	   Level 5: 1
	   Level 6: 1
	   Level 7: 0
	   Level 8: 0
	   Level 9: 0
	   Level 10: 0
You can find the complete log of these tests in /home/gaut/package_check/Complete.log
Global working time for all tests: 44 minutes, 13 seconds (07:46:52).
Disable iptables rules.
Disable the network bridge.
```

Strange I do not see any error in upgrade test, except the result:
```
Upgrade...
Upgrade failed. (1)
The domain already exists
```

**Comment by Gredin67** [comment]
and maybe 
```142325 cp: cannot stat '/etc/matrix-synapse/conf.d/app_service.yaml': No such file or directory
143528 rm: cannot remove '/tmp/app_service_backup.yaml': No such file or directory
```
but I don't think it is raising an error.

**Comment by Gredin67** [comment]
[Complete.log](https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/files/5286381/Complete.log)

**Comment by Gredin67** [comment]
here is my last package_check try from the testing branch:
https://paste.yunohost.org/fipukasojo.xml

I think what is failing is that when restoring from clean install, synapse is not installed again. Thus PostgreSQL is not available:
https://paste.yunohost.org/nowuyeniji.bash

**Comment by tituspijean** [comment]
Oooh, can you try to remove [these lines](https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/blob/29df446522e4d6321bb272432a68e61454b3df6d/scripts/restore#L17-L20) then ?

Edit: Tried it. I have the [dev CI testing it](https://ci-apps-dev.yunohost.org/jenkins/job/mautrix_whatsapp_ynh%20(tituspijean)/1/console).

**Pull request closed without merging**
