### PR TITLE
Add systemd recommended hardening

### PR DESCRIPTION
**Pull request by thardev**
## Description
Added some systemd optional hardening as per recent official docs from Mautrix.
See: https://docs.mau.fi/bridges/go/setup.html?bridge=whatsapp#systemd-service

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Gredin67** [comment]
I cannot help here. I tried with @zamentur to configure this without success. The service never started. 

Le 19 juin 2022 18:52:49 GMT+02:00, Dante ***@***.***> a écrit :
>## Description
>Added some systemd optional hardening as per recent official docs from Mautrix.
>See: https://docs.mau.fi/bridges/go/setup.html?bridge=whatsapp#systemd-service
>
>## PR Status
>
>- [x] Code finished and ready to be reviewed/tested
>- [x] The fix/enhancement were manually tested (if applicable)
>
>## Automatic tests
>
>Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting &quot;!testme&quot;, &quot;!gogogadgetoci&quot; or &quot;By the power of systemd, I invoke The Great App CI to test this Pull Request!&quot;. (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)
>
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/pull/58
>
>-- Commit Summary --
>
>  * Add systemd recommended hardening
>
>-- File Changes --
>
>    M conf/systemd.service (22)
>
>-- Patch Links --
>
>https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/pull/58.patch
>https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/pull/58.diff
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/pull/58
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***&gt;

-- Envoyé depuis /e/ Mail.

**Comment by thardev** [comment]
Hmmm I'll still give it a shot, I'll try to test it on my machines and let's see if I can achieve something. Thanks! :)

**Comment by thardev** [comment]
@Gredin67 I tested it with those new changes related to `home_dir` and it seems to work fine at least on my Bullseye machine.
I'll also test on Buster and check if it also works as expected.
If you want and can test it, feel free to do it :)
Thanks!

**Comment by thardev** [comment]
!testme

**Comment by Gredin67** [comment]
On Yunohost 11 I'm getting 
`juin 22 14:55:59 mautrix-whatsapp[247530]: [Jun 22, 2022 14:55:59] [FATAL] Failed to initialize main database: failed to ensure database owner table exists: stat /home/mautrix_whatsapp/.postgresql/postgresql.crt: permission denied`

**Comment by thardev** [comment]
@Gredin67 yes, did you edit the file manually or tested with this branch?
Because if you edited the file manually on your systemd you should also do something like:
`usermod -d /opt/yunohost/mautrix_whatsapp mautrix_whatsapp`
And then restart the service.

If you used my branch then I'm missing something maybe 😅 I still have to test it properly on my envs

**Comment by Gredin67** [comment]
> you used my branch

I used you branch

**Comment by thardev** [comment]
@Gredin67 did you do it as an upgrade or install from scratch?

**Comment by thardev** [comment]
!testme

**Comment by thardev** [comment]
!testme

**Comment by Gredin67** [comment]
As an upgrade.

Le 23 juin 2022 14:58:33 GMT+02:00, Dante ***@***.***> a écrit :
***@***.*** did you do it as an upgrade or install from scratch?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/pull/58#issuecomment-1164377308
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- Envoyé depuis /e/ Mail.

**Pull request merged**
