### PR TITLE
Upgrade package to version 0.3.0

### PR DESCRIPTION
**Pull request by thardev**
- Upgrade package to version 0.3.0

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Gredin67** [comment]
You can ask to join the organization https://github.com/orgs/YunoHost-Apps/ to be able to trigger the CI and open PR
Or maybe @tituspijean can give you access rights.

**Comment by Gredin67** [comment]
!testme

**Comment by thardev** [comment]
@Gredin67 That would be great! 😄 
I checked the logs of the pipeline and it seems that is failing because of the Synapse package that fails to install 🤔

**Comment by Gredin67** [comment]
I have re-launched the CI which is not super reliable these days. You should have write access now. (thanks @tituspijean )

**Comment by thardev** [comment]
Thanks a lot! 😄

**Comment by thardev** [comment]
!testme

**Comment by thardev** [comment]
I'll wait until https://github.com/YunoHost-Apps/synapse_ynh/issues/304 is solved to merge it.
Pipeline seems to be broken for Synapse install, maybe it will be resolved with https://github.com/YunoHost-Apps/synapse_ynh/pull/297

**Comment by thardev** [comment]
!testme

**Pull request merged**
